# -*- coding: utf-8 -*-
"""Student_Performance 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VjayIHNV6Hr73kdyZQLwddy88F-aEVBy
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("Book1.csv")

df

col = ['math_score', 'reading_score' , 'writing_score','placement_score']

plt.figure(figsize=(10,6))

plt.title("Boxplot of Student Performance Scores")

plt.ylabel("Scores")

df.boxplot(column=['Math_Score', 'Reading_Score', 'Writing_Score', 'Placement_Score'])

print(np.where(df['Reading_Score']>80))

print(np.where(df['Writing_Score']<120))

print(np.where(df['Math_Score']<70))

import matplotlib.pyplot as plt

df = pd.read_csv("Book1.csv")

df

fig, ax = plt.subplots(figsize = (18,10))
ax.scatter(df['Placement_Score'], df['Placement_Offer'])
plt.show()

print(np.where((df['Placement_Score']<80) & (df['Placement_Offer']>1)))

print(np.where((df['Placement_Score']>80) & (df['Placement_Offer']<3)))

import numpy as np
from scipy import stats

z = np.abs(stats.zscore(df['Math_Score']))

z

threshold = 0.18

sample_outliers = np.where(z <threshold)
sample_outliers

import numpy as np

sorted_rscore= sorted(df['Reading_Score'])

sorted_rscore

threshold = 0.18

sample_outliers = np.where(z <threshold)

sample_outliers

q1 = np.percentile(z,25)
q3 = np.percentile(z,75)
iqr = q3 - q1

lwr_bound = q1 - 1.5 * iqr
upr_bound = q3 + 1.5 * iqr

print(lwr_bound, upr_bound)

import numpy as np

sorted_rscore= sorted(df['Reading_Score'])

sorted_rscore

q1 = np.percentile(sorted_rscore, 25)

q3 = np.percentile(sorted_rscore, 75)

q1,q3

sorted_rscore

df = pd.read_csv("Book1.csv")

df.info()

sorted_rscore= sorted(df['Reading_Score'])

sorted_rscore

